server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
