server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}

hystrix.command.findAllProducts.execution.isolation.thread.timeoutInMilliseconds: 6000
hystrix.command.findAllProducts.circuitBreaker.requestVolumeThreshold: 2
hystrix.command.findAllProducts.circuitBreaker.enabled: true
